name: Deploy CI/CD
# on:
#   push:
#     tags:
#       - v*
on:
  push:
    branches: [deploy]

  workflow_dispatch:

jobs:
  main:
    name: Deploy to Firebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create env file
        run: |
          cd functions
          touch .env
          echo "${{ secrets.IPSTACK_API_KEY }}" >> .env
      - name: Install npm packages
        run: |
          cd functions
          npm install
          npm install firebase-tools

      # Deploying the functions to firebase
      - name: Deploy to Firebase
        run: |
          cd functions
          npm run deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
